---
name: Bug report
description: Сообщить об ошибке в материалах или структуре
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Что произошло?
      description: Опишите проблему и ожидаемое поведение
    validations:
      required: true
